spring:
  application:
    name: school-fee-app

  # Align production mail configurations with application.yaml env variables
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

logging:
  level:
    com.fee.app.schoolfeeapp: INFO
    org.springframework.security: WARN

app:
  scheduler:
    outbox-delay: 3600000

